name: Build wheels 

on:
  workflow_dispatch:

jobs:
  build_wheels:
      name: Build wheels on ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-20.04, windows-2019, macOS-10.15]

      steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-python@v2

        - name: Install cibuildwheel
          run: python -m pip install cibuildwheel==2.3.1

        - name: Build wheels
          run: python -m cibuildwheel --output-dir wheelhouse
          env:
            CIBW_TEST_COMMAND: pytest {package}/py/tests

        - uses: actions/upload-artifact@v2
          with:
            path: ./wheelhouse/*.whl
